# For Standings retrival - Once in a hour

reader:
  API_KEY:
  HOST: https://v3.football.api-sports.io
  HEADERS: 
    x-apisports-key: 95df587161b4beedc7f04cfd0a4b0970
  ENDPOINT: /standings
  METHOD: GET
  PARAMS: league=39&season=2022

transformation:
  team_name: (standings.team.name, str)
  team_id: (standings.team.id, int)
  points: (standings.points, int)
  rank: (standings.rank, int)
  played: (standings.all.played, int)
  wins: (standings.all.win, int)
  draws: (standings.all.draw, int)
  losses: (standings.all.lose, int)
  goals_for: (standings.all.goals.for, int)
  goals_against: (standings.all.goals.against, int)
  goal_difference: (standings.goalsDiff, int)
  form: (standings.form, str)
  update_timestamp: (standings.update, str)

writer:
  PROJECT_ID:
  TARGET_TABLE:
  STAGING_TABLE:
  UNIQUE_KEY: standings.team.id




# For Team retrival - Once in a day

reader:
  API_KEY:
  HOST: https://v3.football.api-sports.io
  HEADERS: 
    x-apisports-key: 95df587161b4beedc7f04cfd0a4b0970
  ENDPOINT: /teams
  METHOD: GET
  PARAMS: league=39&season=2022

transformation:
  team_id: (teams.team.id, int)
  team_name: (teams.team.name, str)
  founded_year: (teams.team.founded, int)
  stadium_name: (teams.venue.name, str)
  stadium_city: (teams.venue.city, str)
  stadium_capacity: (teams.venue.capacity, int)

writer:
  PROJECT_ID:
  TARGET_TABLE:
  STAGING_TABLE:
  UNIQUE_KEY: teams.team.id
